export const QUERY_KEYS = {
  PEOPLE: {
    ALL_CHARACTERS: 'PEOPLE_FETCH_DATA',
    CHARACTER_BY_ID: 'PEOPLE_ITEM_FETCH_DATA',
  },
  PLANETS: {
    ALL_PLANETS: 'PLANETS_FETCH_DATA',
    PLANET_BY_ID: 'PLANET_ITEM_FETCH_DATA',
  },
  STARSHIPS: {
    ALL_STARSHIPS: 'STARSHIPS_FETCH_DATA',
    STARSHIP_BY_ID: 'STARSHIP_ITEM_FETCH_DATA',
  },
} as const;
